spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cairenhe?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8
    username: root
    password: free98900667!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

